# Generated by Django 2.2.24 on 2022-02-21 19:14

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_auto_20210823_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color',
            field=colorful.fields.RGBColorField(default='#ffffff', help_text='The RGB color values for the tag.', verbose_name='Color'),
            preserve_default=False,
        ),
    ]
