# Generated by Django 2.2.24 on 2022-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_auto_20220221_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='stylesheet',
            field=models.TextField(blank=True, help_text='The CSS stylesheet to change the appearance of the different user interface elements.', verbose_name='Stylesheet'),
        ),
    ]
