# Generated by Django 2.2.24 on 2022-02-22 06:46

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0006_auto_20220221_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='color',
        ),
        migrations.AddField(
            model_name='theme',
            name='color_background',
            field=colorful.fields.RGBColorField(default='#ffffff', help_text='The RGB color values for the background page.', verbose_name='Color Background page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='color_menu',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for the menu bar.', verbose_name='Color Background Main Menu'),
            preserve_default=False,
        ),
    ]
