# Generated by Django 2.2.24 on 2022-02-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0007_auto_20220222_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CurrentTheme', to='appearance.Theme', verbose_name='CurrentTheme')),
            ],
            options={
                'verbose_name': 'CurrentTheme',
                'verbose_name_plural': 'CurrentTheme',
            },
        ),
    ]
