# Generated by Django 2.2.24 on 2022-03-02 17:17

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0008_currenttheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='color_background',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='color_menu',
        ),
        migrations.AddField(
            model_name='theme',
            name='mainColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for main color.', verbose_name='Color Background Topbar Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='secondColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for second color.', verbose_name='Color Background Main Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='thirdColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for third color.', verbose_name='Color Background Main Menu'),
            preserve_default=False,
        ),
    ]
