# Generated by Django 2.2.24 on 2022-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0009_auto_20220302_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font',
            field=models.CharField(default='default', help_text='Fill name font from google font. If you want default fount please fill "default".', max_length=128, verbose_name='Font for text Logo.'),
            preserve_default=False,
        ),
    ]
