# Generated by Django 2.2.24 on 2022-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0010_theme_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='font',
            field=models.CharField(help_text='Fill font name from <a href = https://fonts.google.com/ target="_blank">Google fonts</a>. If you want default fount please fill "default".', max_length=128, verbose_name='Font for text Logo.'),
        ),
    ]
