# Generated by Django 2.2.24 on 2022-03-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0012_auto_20220305_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='font',
            field=models.CharField(help_text='Fill font name from <a class=\'link_google\' onclick="window.open(\'https://fonts.google.com/\', \'_blank\')"; style="cursor: pointer;">Google fonts</a>. If you want default fount please fill "default".', max_length=128, verbose_name='Font for text Logo.'),
        ),
    ]
